### ISSUE TITLE
problem with delegate/Delegates collection/processDelegates

### ISSUE THREAD

**Issue by pdanpdan** [dperini/nwevents#7] opened 2011-09-23 09:10 UTC
example:

2 forms (id={form1,form2}) with 1 input inside
if you do:
NW.Event.delegate('input','focus',function(e) { console.log('focus1'); },NW.Dom.select('#form1')[0]);
NW.Event.delegate('input','focus',function(e) { console.log('focus2'); },NW.Dom.select('#form2')[0]);

1 - the Delegates collection has a key just for type('focus'), so a listener to call processDelegates is only added for 'form1', so that the focus event for input in form2 is never processed
2 - on focus for #form1 input, both delegated functions are called, as they are both registered for the same type of event (even if they are registered for different elements)

**Comment by pdanpdan** [comment] 2011-09-23 09:19
in processDelegates in these lines:

``` javascript
// if event.target matches one of the registered elements and
// if "this" element matches one of the registered delegates
target = event.target;
// bubble events up to parent nodes
while (target && target != this) {
```

the comment says that this shoul match the registered delegates, but there is no check on this, even if pars[i] is available and not used
so I modified it as:

``` javascript
// if event.target matches one of the registered elements and
// if "this" element matches one of the registered delegates
target = event.target;
// bubble events up to parent nodes
while (parms[i] == this && target && target != this) {
```

**Comment by pdanpdan** [comment] 2011-09-23 09:22
in delegate, I solved the problem by commenting this, even if I don't like the result :(

``` javascript
//if (Delegates[types[i]].items.length === 1) {
  listen(element, types[i], processDelegates, true);
//}
```

but on undelegate I don't have a solution

**Comment by dperini** [comment] 2011-09-23 15:35
Should be fixed now. Please confirm.

Thank you for reporting this issue !

**Comment by pdanpdan** [comment] 2011-09-26 07:14
looks good except the 

``` javascript
if (getRegistered(selector, types[i], element, Delegates).length === 1) {
```

this one checks if there are delegates registered for the element, type AND SELECTOR
I think the selector should not be counted, especially now that the "processDelegates" is registered as handler (so only one)
if I do:

``` javascript
NW.Event.delegate('a','click',function(e) {},element1);
NW.Event.delegate('button','click',function(e) {},element1);
```

"processDelegates" will be registered as handler twice on element1 (in fact the set method will be called twice, but registered once)
in undelegate, if

``` javascript
NW.Event.undelegate('a','click',function(e) {},element1);
```

the handler for "processDelegates" will be unregistered, so no more calls for the second delegate

**Comment by dperini** [comment] 2011-10-04 11:21
@pdanpdan,
I tried to reproduce the fact you talk about but I have been unable to see the problem.

Delegates are added/removed independently based on the passed selector argument.

In your example, I tried removing one delegate and ensured the second one continues to work as expected.

Could you elaborate or provide a simple test case showing the problem ?

I am not sure I completely follow what you said but if there are problems I will definitely try to fix them.

**Comment by pdanpdan** [comment] 2011-10-04 15:11
``` html
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Strict//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en' lang='en'>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <script src='nwmatcher.js' type='text/javascript' charset='utf-8'></script>
    <script src='nwevents.js' type='text/javascript' charset='utf-8'></script>
    <script type="text/javascript">
      NW.Event.appendListener(window, 'load', function() {
        var f = function(e) { console.log('Event: ',e.type,', Target: ',e.target,', this: ',this); },
            d = NW.Dom.byId('interior');
        NW.Event.delegate('div','focus',f,d);
        NW.Event.delegate('input','focus',f,d);
        NW.Event.delegate('textarea','focus',f,d);
        NW.Event.undelegate('textarea','focus',f,d);
        console.log('DOMElements: ',NW.Event.DOMEvents['focus']);
      }, false);
    </script>
    <title>test</title>
  </head>
  <body>
    <div id='exterior'>
      <div id='interior'>
        <input type='text' name='user1' value=''/>
        <textarea name='text1' rows='2' cols='30'></textarea>
      </div>
    </div>
  </body>
</html>
```

1.
With the undelegate line active, NW.Event.DOMEvents['focus'] has no more "processDelegates".
With the undelegate line inactive, NW.Event.DOMEvents['focus'] has "processDelegates" on '#interior'

2.
Why is the delegated function called on 'div#exterior'?

**Comment by pdanpdan** [comment] 2011-10-04 15:50
On a second check, it seems that the unset for processDelegates called in undelegate is not removing the handler because it calls

``` javascript
remove(element, types[i], DOMEvents[types[i]].wraps[k], capture, k);
```

and DOMEvents[types[i]].wraps is empty

so this is the reason the delegation still works

by the way, testing in firefox

**Comment by pdanpdan** [comment] 2011-10-04 15:59
yes, this is it: unset is not removing the handler in case of DOM2 and DOM0 event registration

**Comment by dperini** [comment] 2011-10-04 22:12
@pdanpdan
you are probably getting confused by another "focus" event handler which is installed during "NWEvents" initialization.

The "DOMEvents" you are logging has nothing to do with the delegates you are setting up. It is already there when your code starts, you can copy the same "console.log()" line at the start of your code and you will see it is the same you log at the end. The addition of your delegates does not add any real "focus" event handler, "focus" events are already relayed.

"DOMEvents[types[i]].wraps" should always be empty for Firefox and in general for W3C compliant browsers. It is only needed/filled for IE < 9 to avoid leaks and to make it easier to remove handlers (to keep handlers references).

> Why is delegated function called on 'div#exterior'?

No function handler are invoked for 'div#exterior'. It is the value of the "this" keyword during the event propagation.

During capture, events travel from top (window/document) and they propagate down to the target element then bubble up back again. You can check that by logging the ".eventPhase" property of the event object.

Also be aware that the "this" keyword works differently than expected from normal event dispatched "AT_TARGET".
Only "AT_TARGET" the "this" keyword contains reference to the element on which the handler was hooked. With "delegation", to get a reference to the element on which the handler was installed you need to use the ".currentTarget" property of the event object.

Let me know if these points do solve your doubts.

**Comment by dperini** [comment] 2011-10-04 23:04
There is a mistake in my explanation above.

The "this" keyword should never be "div#exterior" since the "top" element for the delegation is "#div#interior" (a descendant). So, it seems there is still something wrong. I primarily thought your where delegating on "document".

Maybe I am not considering the fourth parameter as the "top" element and I cross that boundary.

That would explain the "this" keyword assuming the wrong reference to "div#exterior"

**Closed as completed by dperini** 2011-10-04 23:04 UTC

**Comment by pdanpdan** [comment] 2011-10-05 03:47
1. sorrry to bother you, but about unset method, it's not really removing the handler for DOM0/DOM2, here is an example:

``` html
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Strict//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en' lang='en'>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <script src='nwmatcher.js' type='text/javascript' charset='utf-8'></script>
    <script src='nwevents.js' type='text/javascript' charset='utf-8'></script>
    <script type="text/javascript">
      NW.Event.appendListener(window, 'load', function() {
        var f = function(e) { console.log('Event called'); },
            d = NW.Dom.byId('target');
        NW.Event.set(d,'click',f);
        NW.Event.unset(d,'click',f);
      }, false);
    </script>
    <title>test</title>
  </head>
  <body>
    <div id='target'>
      TARTGET - CLICK on me (my handler was set and then unset)
    </div>
  </body>
</html>
```
1. In the first example (the one with delegate/undelegate), if you remove the line with "NW.Event.undelegate('textarea','focus',f,d);" you will see that NW.Event.DOMEvents['focus'] has "processDelegates" on '#interior'
2. That's exactly what I meant - the call to the delegated function is crossing the boundary up
3. The check to see if delegate needs to register/unregister the processDelegate function on the delegated element contains this: 

``` javascript
if (getRegistered(selector, types[i], element, Delegates).length === 1) {
  set(element, types[i], processDelegates, true);
}
```

As I understand it, this checks if there is only 1 delegated function registered for (selector,types[i],element).
So, for this:
- delegate('selector1','type1,'element1');
- delegate('selector2','type1,'element1');
  it would call set('element1', 'type1', 'processDelegates') twice, and for
- delegate('selector1','type1,'element1');
- delegate('selector2','type1,'element1');
- undelegate('selector2','type1,'element1');
  it would call set('element1', 'type1', 'processDelegates') twice and then unset('element1', 'type1', 'processDelegates') - except that unset does nothing now, so the delegation still seems to work

**Comment by dperini** [comment] 2011-10-05 20:22
OK, I just did commit a couple of tentative fixes for both problems you observed. Let's run some test now !

Thank you for noticing this hidden misbehaviour and provide test cases & very helpful suggestions.

**Comment by pdanpdan** [comment] 2011-10-06 06:45
Seems to be working fine now, thank you!

**Comment by pdanpdan** [comment] 2011-10-07 12:14
My bad, I haven't checked it as it should.
There is still a problem:
delegate/undelegate checks if it should add/remove listener by calling getRegistered
`if (getRegistered('*', types[i], element, Delegates).length === 1) {`
but in getRegistered, if `object === '*'` it considers it matched and it doesn't check for `register[i].parms[j] === capture` any more, so that if I try to delegate the same event to 2 elements, it doesn't register the second listener (for the second element)

**Comment by pdanpdan** [comment] 2011-10-07 12:46
If I think about it, maybe it would be more consistent if in Delegates information would be stored with delegated element in items[] and selector in parms[]

**Comment by dperini** [comment] 2011-10-09 23:10
Ok, I have rewritten that part taking in consideration the consistency thing you suggested above.

Before committing I would like you (and possibly others) to test out this preview I have just rewritten:

```
http://dl.dropbox.com/u/598365/Preview/nwevents.js
```

I repeated most of the tests I have and it seems working without backward incompatibilities.

Thank you very much for your help debugging.

**Comment by pdanpdan** [comment] 2011-10-10 06:54
Seems to be working fine now, thank you.
I'll try and build a test suite and contact you later.
